name: GuillimanUtils
main: io.github.RESKOM326.guillimanutils.GuillimanUtils
version: 0.0.1-SNAPSHOT
author: RESKOM326
website: https://reskom326.github.io/
commands:
   ignite:
      aliases: [cleanse, purge]
      description: Sets on fire a player for an amount of time measured in seconds
      usage: /ignite <player> <time>
      permission: GuillimanUtils.ignite
      permission-message: You do not have permissions to execute this command
   hideme:
      aliases: [hidefrom]
      description: Hides a player from every player or either the chosen players
      usage: /hideme [player 1] [player 2] ... [player N]
      permission: GuillimanUtils.hideme
      permission-message: You do not have permissions to execute this command
   unhideme:
      aliases: [showme, showfrom]
      description: Unhides a player from every player or either the chosen players
      usage: /unhideme [player 1] [player 2] ... [player N]
      permission: GuillimanUtils.unhideme
      permission-message: You do not have permissions to execute this command
permissions:
   GuillimanUtils.*:
      description: Grants access to all GuillimanUtils' commands
      children:
         GuillimanUtils.ignite: true
         GuillimanUtils.hideme: true
         GuillimanUtils.unhideme: true
   GuillimanUtils.ignite:
      default: op
   GuillimanUtils.hideme:
      default: op
   GuillimanUtils.unhideme:
      default: op
